const supportedIsoCurrencies = <String>[
  'AED',
  'ARS',
  'AUD',
  'BGN',
  'BRL',
  'CAD',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CZK',
  'DKK',
  'EUR',
  'GBP',
  'HKD',
  'HRK',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'ISK',
  'JPY',
  'KRW',
  'MXN',
  'MYR',
  'NOK',
  'NZD',
  'PLN',
  'PHP',
  'RON',
  'RUB',
  'SAR',
  'SEK',
  'SGD',
  'THB',
  'TRY',
  'TWD',
  'USD',
  'ZAR',
];

const _countryCurrencyDefaults = <String, String>{
  'australien': 'AUD',
  'australia': 'AUD',
  'china': 'CNY',
  'dänemark': 'DKK',
  'denmark': 'DKK',
  'deutschland': 'EUR',
  'germany': 'EUR',
  'eu': 'EUR',
  'europäische union': 'EUR',
  'european union': 'EUR',
  'frankreich': 'EUR',
  'france': 'EUR',
  'großbritannien': 'GBP',
  'great britain': 'GBP',
  'hongkong': 'HKD',
  'hong kong': 'HKD',
  'italien': 'EUR',
  'italy': 'EUR',
  'japan': 'JPY',
  'kanada': 'CAD',
  'canada': 'CAD',
  'neuseeland': 'NZD',
  'new zealand': 'NZD',
  'norwegen': 'NOK',
  'norway': 'NOK',
  'österreich': 'EUR',
  'austria': 'EUR',
  'polen': 'PLN',
  'poland': 'PLN',
  'schweden': 'SEK',
  'sweden': 'SEK',
  'schweiz': 'CHF',
  'switzerland': 'CHF',
  'singapur': 'SGD',
  'singapore': 'SGD',
  'spanien': 'EUR',
  'spain': 'EUR',
  'tschechien': 'CZK',
  'czech republic': 'CZK',
  'türkei': 'TRY',
  'turkey': 'TRY',
  'ungarn': 'HUF',
  'hungary': 'HUF',
  'usa': 'USD',
  'us': 'USD',
  'united states': 'USD',
  'united states of america': 'USD',
  'vereinigte staaten': 'USD',
  'vereinigtes königreich': 'GBP',
  'united kingdom': 'GBP',
};

String normalizeCountry(String value) => value.trim().toLowerCase();

String defaultCurrencyForCountry(String? country, {String fallback = 'EUR'}) {
  final normalized = normalizeCountry(country ?? '');
  return _countryCurrencyDefaults[normalized] ?? fallback.toUpperCase();
}

bool isSupportedCurrency(String value) =>
    supportedIsoCurrencies.contains(value.trim().toUpperCase());
