import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../application/providers.dart';
import '../../domain/models.dart';
import '../widgets.dart';

class LedgerPage extends ConsumerWidget { const LedgerPage({super.key});
  Future<void> _add(BuildContext context, WidgetRef ref) async { final amount = await textPrompt(context, 'Ausgabe erfassen', 'Betrag in EUR'); if (amount == null || !context.mounted) return; final category = await textPrompt(context, 'Ausgabe erfassen', 'Kategorie'); if (category == null || category.isEmpty || !context.mounted) return; final merchant = await textPrompt(context, 'Ausgabe erfassen', 'Händler'); if (merchant == null) return; await ref.read(financeProvider.notifier).addEntry(amount: ((double.tryParse(amount.replaceAll(',', '.')) ?? 0) * 100).round(), kind: TransactionKind.expense, category: category, merchant: merchant); }
  @override Widget build(BuildContext context, WidgetRef ref) => Padding(padding: const EdgeInsets.all(24), child: Column(children: [PageHeading('Haushaltsbuch', subtitle: 'Einnahmen und Ausgaben im Blick.', action: FilledButton.icon(onPressed: () => _add(context, ref), icon: const Icon(Icons.add), label: const Text('Buchung'))), const SizedBox(height: 20), Expanded(child: ref.watch(financeProvider).when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Text('$e'), data: (data) { final entries = [...data.entries]..sort((a, b) => b.date.compareTo(a.date)); if (entries.isEmpty) return const EmptyState(icon: Icons.receipt_long, title: 'Keine Buchungen', message: 'Erfasse deine erste Einnahme oder Ausgabe.'); return ListView.builder(itemCount: entries.length, itemBuilder: (_, i) { final e = entries[i]; final expense = e.kind == TransactionKind.expense; return ListTile(leading: CircleAvatar(backgroundColor: expense ? Colors.red.withValues(alpha: .12) : Colors.green.withValues(alpha: .12), child: Icon(expense ? Icons.arrow_upward : Icons.arrow_downward, color: expense ? Colors.red : Colors.green)), title: Text(e.category, style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Text('${e.merchant} · ${DateFormat.yMMMd('de').format(e.date)}'), trailing: Row(mainAxisSize: MainAxisSize.min, children: [Text('${expense ? '−' : '+'}${money(e.amount)}', style: const TextStyle(fontWeight: FontWeight.w800)), IconButton(onPressed: () => ref.read(financeProvider.notifier).removeEntry(e.id), icon: const Icon(Icons.close))])); }); }))])); }
