import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../application/providers.dart';
import '../../domain/calculations.dart';
import '../widgets.dart';

class MorePage extends StatelessWidget { const MorePage({super.key});
  @override Widget build(BuildContext context) { final items = [
    ('Dividenden', Icons.payments_outlined, const DividendsPage()), ('ETF-Rechner', Icons.calculate_outlined, const CalculatorPage()), ('Fahrzeuge', Icons.directions_car_outlined, const VehiclesPage()), ('Fahrtkosten', Icons.route_outlined, const TripCalculatorPage()), ('Import & Export', Icons.import_export, const TransferPage()), ('Einstellungen', Icons.settings_outlined, const SettingsPage()),
  ]; return Padding(padding: const EdgeInsets.all(24), child: Column(children: [const PageHeading('Mehr', subtitle: 'Rechner, Mobilität, Datenaustausch und Einstellungen.'), const SizedBox(height: 20), Expanded(child: GridView.builder(gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 340, mainAxisExtent: 130, crossAxisSpacing: 14, mainAxisSpacing: 14), itemCount: items.length, itemBuilder: (_, i) => Card(child: InkWell(borderRadius: BorderRadius.circular(24), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => items[i].$3)), child: Padding(padding: const EdgeInsets.all(20), child: Row(children: [Icon(items[i].$2, size: 32, color: Theme.of(context).colorScheme.primary), const SizedBox(width: 16), Expanded(child: Text(items[i].$1, style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700))), const Icon(Icons.chevron_right)])))))])); }
}

class _SubPage extends StatelessWidget { const _SubPage({required this.title, required this.child}); final String title; final Widget child; @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(title)), body: SafeArea(child: child)); }

class DividendsPage extends ConsumerWidget { const DividendsPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) => _SubPage(title: 'Dividenden', child: ref.watch(financeProvider).when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Text('$e'), data: (data) => data.positions.isEmpty ? const EmptyState(icon: Icons.payments, title: 'Keine Ausschüttungen', message: 'Dividenden werden den Wertpapierpositionen zugeordnet.') : ListView(padding: const EdgeInsets.all(24), children: [const PageHeading('Dividendenübersicht', subtitle: 'Monatliche und jährliche Ausschüttungen.'), const SizedBox(height: 20), ...data.positions.map((p) => Card(child: ListTile(title: Text(p.name), subtitle: Text(p.symbol), trailing: const Text('Keine Ereignisse'))))]))); }

class CalculatorPage extends StatefulWidget { const CalculatorPage({super.key}); @override State<CalculatorPage> createState() => _CalculatorPageState(); }
class _CalculatorPageState extends State<CalculatorPage> { double start = 10000, monthly = 300, rate = 6; int years = 20; @override Widget build(BuildContext context) { final result = compoundInterest(initialCapital: start, monthlyContribution: monthly, annualRatePercent: rate, years: years); return _SubPage(title: 'ETF-Rechner', child: ListView(padding: const EdgeInsets.all(24), children: [const PageHeading('Zinseszins', subtitle: 'Berechne die Entwicklung deines Sparplans.'), const SizedBox(height: 20), _slider('Startkapital', start, 0, 100000, (v) => setState(() => start = v), money(start.round() * 100)), _slider('Monatliche Sparrate', monthly, 0, 3000, (v) => setState(() => monthly = v), money(monthly.round() * 100)), _slider('Rendite', rate, 0, 15, (v) => setState(() => rate = v), '${rate.toStringAsFixed(1)} %'), _slider('Laufzeit', years.toDouble(), 1, 50, (v) => setState(() => years = v.round()), '$years Jahre'), const SizedBox(height: 16), Card(child: Padding(padding: const EdgeInsets.all(24), child: Column(children: [Text('Endkapital', style: Theme.of(context).textTheme.titleMedium), Text(money((result.finalCapital * 100).round()), style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w900)), const Divider(height: 32), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Einzahlungen'), Text(money((result.deposits * 100).round()))]), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Gewinn'), Text(money((result.profit * 100).round()))])])))])); }
  Widget _slider(String label, double value, double min, double max, ValueChanged<double> change, String formatted) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(label), Text(formatted, style: const TextStyle(fontWeight: FontWeight.w800))]), Slider(value: value.clamp(min, max), min: min, max: max, onChanged: change)])));
}

class VehiclesPage extends ConsumerWidget { const VehiclesPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) => _SubPage(title: 'Fahrzeuge', child: Padding(padding: const EdgeInsets.all(24), child: Column(children: [PageHeading('Auto & Motorrad', action: FilledButton.icon(onPressed: () async { final name = await textPrompt(context, 'Fahrzeug hinzufügen', 'Marke und Modell'); if (name == null || name.isEmpty || !context.mounted) return; await ref.read(financeProvider.notifier).addVehicle(name: name, kind: 'Auto', year: DateTime.now().year); }, icon: const Icon(Icons.add), label: const Text('Fahrzeug'))), const SizedBox(height: 20), Expanded(child: ref.watch(financeProvider).when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Text('$e'), data: (data) => data.vehicles.isEmpty ? const EmptyState(icon: Icons.garage_outlined, title: 'Keine Fahrzeuge', message: 'Füge Auto oder Motorrad hinzu.') : ListView(children: data.vehicles.map((v) => Card(child: ListTile(leading: Icon(v.kind == 'Auto' ? Icons.directions_car : Icons.two_wheeler), title: Text(v.name), subtitle: Text('${v.kind} · ${v.year}'), trailing: Text(money(v.cost))))).toList())))])));
}

class TripCalculatorPage extends StatefulWidget { const TripCalculatorPage({super.key}); @override State<TripCalculatorPage> createState() => _TripCalculatorPageState(); }
class _TripCalculatorPageState extends State<TripCalculatorPage> { double km = 30, consumption = 7, price = 1.75, trips = 5; @override Widget build(BuildContext context) { final result = tripCosts(kilometers: km, litersPer100Km: consumption, pricePerLiter: price, tripsPerWeek: trips); return _SubPage(title: 'Fahrtkosten', child: ListView(padding: const EdgeInsets.all(24), children: [const PageHeading('Fahrtkostenrechner'), _input('Kilometer', km, (v) => km = v), _input('Verbrauch l/100 km', consumption, (v) => consumption = v), _input('Kraftstoffpreis', price, (v) => price = v), _input('Fahrten pro Woche', trips, (v) => trips = v), Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(children: [_result('Pro Fahrt', result.perTrip), _result('Pro Woche', result.perWeek), _result('Pro Monat', result.perMonth), _result('Pro Jahr', result.perYear)])))])); } Widget _input(String label, double initial, ValueChanged<double> set) => Padding(padding: const EdgeInsets.only(top: 12), child: TextFormField(initialValue: initial.toString(), keyboardType: TextInputType.number, decoration: InputDecoration(labelText: label), onChanged: (v) => setState(() => set(double.tryParse(v.replaceAll(',', '.')) ?? 0)))); Widget _result(String label, double value) => Padding(padding: const EdgeInsets.symmetric(vertical: 6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(label), Text(money((value * 100).round()), style: const TextStyle(fontWeight: FontWeight.w800))])); }

class TransferPage extends ConsumerWidget { const TransferPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) => _SubPage(title: 'Import & Export', child: ListView(padding: const EdgeInsets.all(24), children: [const PageHeading('Deine Daten', subtitle: 'Portables, versioniertes JSON-Format.'), const SizedBox(height: 20), ListTile(leading: const Icon(Icons.copy_all), title: const Text('JSON exportieren'), subtitle: const Text('In die Zwischenablage kopieren'), onTap: () async { await Clipboard.setData(ClipboardData(text: ref.read(financeProvider.notifier).exportJson())); if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Export kopiert'))); }), ListTile(leading: const Icon(Icons.content_paste), title: const Text('JSON importieren'), subtitle: const Text('Aus der Zwischenablage übernehmen'), onTap: () async { final value = (await Clipboard.getData('text/plain'))?.text; if (value == null) return; try { await ref.read(financeProvider.notifier).importJson(value); if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Import abgeschlossen'))); } catch (_) { if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Ungültige Importdatei'))); } })])); }

class SettingsPage extends ConsumerWidget { const SettingsPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final selected = ref.watch(themeProvider).valueOrNull ?? ThemeMode.system; return _SubPage(title: 'Einstellungen', child: ListView(padding: const EdgeInsets.all(24), children: [const PageHeading('Einstellungen'), const SizedBox(height: 20), Text('Darstellung', style: Theme.of(context).textTheme.titleMedium), ...ThemeMode.values.map((mode) => RadioListTile<ThemeMode>(value: mode, groupValue: selected, onChanged: (v) { if (v != null) ref.read(themeProvider.notifier).set(v); }, title: Text({'system': 'System', 'light': 'Hell', 'dark': 'Dunkel'}[mode.name]!))), const Divider(), const ListTile(leading: Icon(Icons.language), title: Text('Sprache'), trailing: Text('Deutsch')), const ListTile(leading: Icon(Icons.euro), title: Text('Basiswährung'), trailing: Text('EUR')), const ListTile(leading: Icon(Icons.cloud_off), title: Text('Datenmodus'), subtitle: Text('Lokal – Daten bleiben auf diesem Gerät')), const ListTile(leading: Icon(Icons.security), title: Text('Datenschutz'), subtitle: Text('Keine Analyse- oder Werbetracker'))])); } }
