import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../application/providers.dart';
import '../../domain/models.dart';
import '../widgets.dart';

class PortfolioPage extends ConsumerStatefulWidget { const PortfolioPage({super.key}); @override ConsumerState<PortfolioPage> createState() => _PortfolioPageState(); }
class _PortfolioPageState extends ConsumerState<PortfolioPage> {
  AssetType? filter;
  Future<void> _add() async { final name = await textPrompt(context, 'Position hinzufügen', 'Name'); if (name == null || name.isEmpty || !mounted) return; final symbol = await textPrompt(context, 'Position hinzufügen', 'Symbol'); if (symbol == null || !mounted) return; final quantity = await textPrompt(context, 'Stückzahl', 'Anzahl'); if (quantity == null || !mounted) return; final price = await textPrompt(context, 'Kaufkurs', 'EUR je Stück'); if (price == null) return; final cents = ((double.tryParse(price.replaceAll(',', '.')) ?? 0) * 100).round(); await ref.read(financeProvider.notifier).addPosition(name: name, symbol: symbol, type: AssetType.stock, quantity: double.tryParse(quantity.replaceAll(',', '.')) ?? 0, purchasePrice: cents, currentPrice: cents); }
  @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.all(24), child: Column(children: [PageHeading('Portfolio', subtitle: 'Positionen, Werte und Performance.', action: FilledButton.icon(onPressed: _add, icon: const Icon(Icons.add), label: const Text('Position'))), const SizedBox(height: 14), SizedBox(height: 42, child: ListView(scrollDirection: Axis.horizontal, children: [ChoiceChip(label: const Text('Alle'), selected: filter == null, onSelected: (_) => setState(() => filter = null)), const SizedBox(width: 8), ...AssetType.values.map((type) => Padding(padding: const EdgeInsets.only(right: 8), child: ChoiceChip(label: Text(type.name), selected: filter == type, onSelected: (_) => setState(() => filter = type))))])), const SizedBox(height: 12), Expanded(child: ref.watch(financeProvider).when(loading: () => const Center(child: CircularProgressIndicator()), error: (e, _) => Text('$e'), data: (data) { final positions = data.positions.where((e) => filter == null || e.type == filter).toList()..sort((a, b) => b.value.compareTo(a.value)); if (positions.isEmpty) return const EmptyState(icon: Icons.candlestick_chart, title: 'Keine Positionen', message: 'Erfasse dein erstes Wertpapier oder ändere den Filter.'); return ListView.builder(itemCount: positions.length, itemBuilder: (_, i) { final item = positions[i]; return Card(child: ListTile(contentPadding: const EdgeInsets.all(18), leading: CircleAvatar(child: Text(item.symbol.characters.take(2).toString().toUpperCase())), title: Text(item.name, style: const TextStyle(fontWeight: FontWeight.w700)), subtitle: Text('${item.quantity} Stück · ${item.type.name}'), trailing: Row(mainAxisSize: MainAxisSize.min, children: [Column(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Text(money(item.value), style: const TextStyle(fontWeight: FontWeight.w800)), Text('${item.performance.toStringAsFixed(2)} %', style: TextStyle(color: item.gain >= 0 ? Colors.green : Colors.red))]), IconButton(onPressed: () => ref.read(financeProvider.notifier).removePosition(item.id), icon: const Icon(Icons.delete_outline))])); }); }))]));
}
